# build environment
FROM node:13.12.0-alpine as build

MAINTAINER Cynthion Mahavonjy <mahavonjy.cynthion@gmail.com>

COPY . /usr/src/app/
WORKDIR /usr/src/app/

RUN rm -rf node_modules && npm install --silent && npm install -g serve
RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /usr/src/app/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
